"""
Byte-Level Transformer Model
Processes raw bytes (0-255) instead of tokens - no tokenizer needed!

Advantages:
- No vocabulary limitations
- Perfect multilingual support
- Handles any data type (text, code, binary)
- No tokenization overhead
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Optional, Tuple
import math


class ByteLevelTransformer(nn.Module):
    """
    Transformer that operates on raw bytes (0-255)

    Key differences from token-based transformers:
    - Vocabulary size: 256 (not 50k+)
    - Input: Raw UTF-8 bytes
    - Output: Next byte prediction (256-way classification)
    """

    def __init__(
        self,
        d_model: int = 512,
        nhead: int = 8,
        num_layers: int = 12,
        dim_feedforward: int = 2048,
        dropout: float = 0.1,
        max_seq_length: int = 8192,
        use_flash_attention: bool = False
    ):
        super().__init__()

        self.d_model = d_model
        self.max_seq_length = max_seq_length

        # Byte embedding (only 256 possible values!)
        self.byte_embedding = nn.Embedding(256, d_model)

        # Learnable positional encoding
        self.pos_embedding = nn.Embedding(max_seq_length, d_model)

        # Dropout
        self.dropout = nn.Dropout(dropout)

        # Transformer encoder layers
        encoder_layer = TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            use_flash_attention=use_flash_attention
        )

        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers,
            norm=nn.LayerNorm(d_model)
        )

        # Output projection to byte space
        self.output_projection = nn.Linear(d_model, 256)

        # Initialize weights
        self._init_weights()

    def _init_weights(self):
        """Initialize weights with small values"""
        for p in self.parameters():
            if p.dim() > 1:
                nn.init.xavier_uniform_(p)

    def forward(
        self,
        byte_ids: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        return_embeddings: bool = False
    ) -> torch.Tensor:
        """
        Forward pass

        Args:
            byte_ids: [batch_size, seq_len] of byte values (0-255)
            attention_mask: [batch_size, seq_len] optional mask
            return_embeddings: If True, return embeddings instead of logits

        Returns:
            logits: [batch_size, seq_len, 256] next byte predictions
            or embeddings: [batch_size, seq_len, d_model] if return_embeddings=True
        """
        batch_size, seq_len = byte_ids.shape

        # Byte embeddings
        byte_embeds = self.byte_embedding(byte_ids)  # [B, L, D]

        # Positional embeddings
        positions = torch.arange(seq_len, device=byte_ids.device).unsqueeze(0)
        pos_embeds = self.pos_embedding(positions)  # [1, L, D]

        # Combine
        x = byte_embeds + pos_embeds
        x = self.dropout(x)

        # Create causal mask (lower triangular)
        causal_mask = self._generate_square_subsequent_mask(seq_len, byte_ids.device)

        # Transformer
        x = self.transformer_encoder(
            x,
            mask=causal_mask,
            src_key_padding_mask=attention_mask
        )

        if return_embeddings:
            return x

        # Project to byte probabilities
        logits = self.output_projection(x)  # [B, L, 256]

        return logits

    def _generate_square_subsequent_mask(self, sz: int, device: torch.device) -> torch.Tensor:
        """Generate causal mask for autoregressive generation"""
        mask = torch.triu(torch.ones(sz, sz, device=device), diagonal=1)
        mask = mask.masked_fill(mask == 1, float('-inf'))
        return mask

    @torch.inference_mode()
    def generate(
        self,
        prompt_bytes: list,
        max_new_bytes: int = 256,
        temperature: float = 1.0,
        top_k: int = 50,
        top_p: float = 0.9,
        repetition_penalty: float = 1.0,
        device: str = "cuda"
    ) -> list:
        """
        Generate bytes autoregressively

        Args:
            prompt_bytes: List of byte values (0-255)
            max_new_bytes: Maximum bytes to generate
            temperature: Sampling temperature (higher = more random)
            top_k: Keep only top k logits
            top_p: Nucleus sampling threshold
            repetition_penalty: Penalize repeated bytes
            device: Device to run on

        Returns:
            List of generated byte values
        """
        self.eval()

        # Convert to tensor
        current = torch.tensor([prompt_bytes], dtype=torch.long, device=device)

        generated_bytes = []
        byte_counts = {}

        for step in range(max_new_bytes):
            # Truncate if too long
            if current.size(1) > self.max_seq_length:
                current = current[:, -self.max_seq_length:]

            # Forward pass
            logits = self.forward(current)
            next_byte_logits = logits[0, -1, :] / temperature

            # Apply repetition penalty
            if repetition_penalty != 1.0:
                for byte_val, count in byte_counts.items():
                    next_byte_logits[byte_val] /= (repetition_penalty ** count)

            # Top-k filtering
            if top_k > 0:
                indices_to_remove = next_byte_logits < torch.topk(next_byte_logits, top_k)[0][..., -1, None]
                next_byte_logits[indices_to_remove] = float('-inf')

            # Top-p (nucleus) filtering
            if top_p < 1.0:
                sorted_logits, sorted_indices = torch.sort(next_byte_logits, descending=True)
                cumulative_probs = torch.cumsum(F.softmax(sorted_logits, dim=-1), dim=-1)

                sorted_indices_to_remove = cumulative_probs > top_p
                sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[..., :-1].clone()
                sorted_indices_to_remove[..., 0] = 0

                indices_to_remove = sorted_indices[sorted_indices_to_remove]
                next_byte_logits[indices_to_remove] = float('-inf')

            # Sample
            probs = F.softmax(next_byte_logits, dim=-1)
            next_byte = torch.multinomial(probs, num_samples=1)

            byte_val = next_byte.item()

            # Track byte counts for repetition penalty
            byte_counts[byte_val] = byte_counts.get(byte_val, 0) + 1

            # Append to sequence
            current = torch.cat([current, next_byte.unsqueeze(0)], dim=1)
            generated_bytes.append(byte_val)

            # Stop on null byte or newline (optional)
            if byte_val == 0:
                break

        return prompt_bytes + generated_bytes

    def get_num_params(self) -> int:
        """Count trainable parameters"""
        return sum(p.numel() for p in self.parameters() if p.requires_grad)


class TransformerEncoderLayer(nn.Module):
    """
    Custom transformer layer with optional Flash Attention
    """

    def __init__(
        self,
        d_model: int,
        nhead: int,
        dim_feedforward: int,
        dropout: float = 0.1,
        use_flash_attention: bool = False
    ):
        super().__init__()

        self.self_attn = nn.MultiheadAttention(
            d_model,
            nhead,
            dropout=dropout,
            batch_first=True
        )

        # Feed-forward network
        self.linear1 = nn.Linear(d_model, dim_feedforward)
        self.dropout = nn.Dropout(dropout)
        self.linear2 = nn.Linear(dim_feedforward, d_model)

        # Layer norms
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)

        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)

    def forward(
        self,
        src: torch.Tensor,
        src_mask: Optional[torch.Tensor] = None,
        src_key_padding_mask: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        """Forward pass with pre-norm architecture"""

        # Self-attention with residual
        src2 = self.norm1(src)
        src2, _ = self.self_attn(
            src2, src2, src2,
            attn_mask=src_mask,
            key_padding_mask=src_key_padding_mask
        )
        src = src + self.dropout1(src2)

        # Feed-forward with residual
        src2 = self.norm2(src)
        src2 = self.linear2(self.dropout(F.gelu(self.linear1(src2))))
        src = src + self.dropout2(src2)

        return src


def create_byte_model(
    model_size: str = "small",
    max_seq_length: int = 8192
) -> ByteLevelTransformer:
    """
    Create byte-level model with predefined sizes

    Args:
        model_size: "tiny", "small", "medium", "large", "xl"
        max_seq_length: Maximum sequence length

    Returns:
        ByteLevelTransformer model
    """

    configs = {
        "tiny": {
            "d_model": 256,
            "nhead": 4,
            "num_layers": 6,
            "dim_feedforward": 1024
        },
        "small": {
            "d_model": 512,
            "nhead": 8,
            "num_layers": 12,
            "dim_feedforward": 2048
        },
        "medium": {
            "d_model": 768,
            "nhead": 12,
            "num_layers": 16,
            "dim_feedforward": 3072
        },
        "large": {
            "d_model": 1024,
            "nhead": 16,
            "num_layers": 24,
            "dim_feedforward": 4096
        },
        "xl": {
            "d_model": 1536,
            "nhead": 24,
            "num_layers": 32,
            "dim_feedforward": 6144
        }
    }

    if model_size not in configs:
        raise ValueError(f"Unknown model size: {model_size}")

    config = configs[model_size]
    model = ByteLevelTransformer(
        **config,
        max_seq_length=max_seq_length
    )

    num_params = model.get_num_params()
    print(f"Created {model_size} model with {num_params:,} parameters")

    return model


if __name__ == "__main__":
    # Demo
    print("Byte-Level Transformer Demo\n")

    # Create small model
    model = create_byte_model("small", max_seq_length=2048)

    # Test text
    text = "Hello, world! This is a byte-level model."
    bytes_input = list(text.encode('utf-8'))

    print(f"Input text: {text}")
    print(f"Input bytes: {bytes_input}")
    print(f"Num bytes: {len(bytes_input)}")

    # Generate
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device)

    print(f"\nGenerating on {device}...")
    generated = model.generate(
        prompt_bytes=bytes_input,
        max_new_bytes=50,
        temperature=0.8,
        device=device
    )

    # Decode
    try:
        output_text = bytes(generated).decode('utf-8', errors='ignore')
        print(f"\nGenerated text:\n{output_text}")
    except:
        print(f"\nGenerated bytes: {generated}")
